### ISSUE TITLE
Easily digestible data - [Thomas the Policy Advisory] - [3]

### ISSUE THREAD

**Issue by Leo-Bol** [code4policy/Team-A4#2]
**As a** Policy Advisor in a major international organization

**I want** rapid access to easily digestible and credible data that I can copy and paste into a policy report

**So that** my policymaker can rapidly digest the stakes behind the sector without having to read more than 2 or 3 pages

------------------------------
**INVEST**
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

-------
**Definition of done:**

- [ ] Making a concise website that the policymaker with less familiarity with the topic can read easily.
- [x] Making graphs that the policymaker can use immediately [moved to other issue]

------
**Tasks:**

- [ ] Check if there is any paragraph that is so long to take time to read
- [ ] Shorten the paragraph 
- [ ] Making footnotes to professional words in all sections
- [ ] link to rawdata
- [x] Making sure that all graphs include footnotes and references so that policymaker can paste at once [moved to other issue]
