### ISSUE TITLE
Financials-focused data - [Sarah the Venture Capitalist] - [13]

### ISSUE THREAD

**Issue by QuentinGollier** [code4policy/Team-A4#3]
**As** an Associate at a major VC fund

**I want** to be able to see quickly where the industry is going and how fast it's moving (historical perspective)

**So that** I can plug data in my sectorial report that make sense to my VP and Partner
-------

------------------------------
**INVEST**
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

-------
**Definition of done:**

 - [x] Text is there
 - [x] Text is in clearly defined sections
 - [x] Each section has a very clear reference

------
**Tasks:**

- [x] Select the data (e.g revenue of space startups or investments into space start ups)
- [x]  define the scope (e.g. countries and time frame, ideally consistent with other section)
- [x]  Define the sections
 - [x] Define content of the sections
 - [x] Insert content into the page
