### ISSUE TITLE
Easy to understand - [Sam the Graduate Student] - [5]

### ISSUE THREAD

**Issue by KaoriOchi** [code4policy/Team-A4#4]
**As a** Graduate Student in a tech university

**I want** to grasp the overview of the satellite industry

**So that** all sentence should be easy to read and be written without terminology or with explanations of terminology

------------------------------
**INVEST**
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

-------

**Definition of done:**

- [ ] All contents are clearly visualized.
- [ ] URL is anchored
- [ ] Clear explanations of the terminology are provided below the contents 
- [ ] Have "download csv" button 

------

**Tasks:**

- [x] Focus on major events to avoid overcomplicating things 
- [ ] All texts are large enough to see
- [ ] Use colors that are easy for people with color blindness
- [ ] Insert content into the page

**Comment by Leo-Bol** [comment]
De-prioritized - hence not edited for second user story planning
