### ISSUE TITLE
Exhaustively referenced data [Thomas, Sarah]

### ISSUE THREAD

**Issue by QuentinGollier** [code4policy/Team-A4#56]

**Comment by QuentinGollier** [comment]
**As** people who need to ensure they are fully backed-up on their data

**We want** a narrative that's completely sourced

**So that** we don't have to worry about being blindsided by what we pull from the website


------------------------------
**INVEST**
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

-------
**Definition of done:**
- [x] Every section displays clearly its sources, with links
- [x] The website is data-transparent: it is clear where the data comes from

------
**Tasks:**

- [x] Ensure that there is a set element in the section where sources will be located
- [x] Fill the element with the section's sources
- [x] Insert code into the website's main branch
