### ISSUE TITLE
Clear dynamic narrative - [Sarah & Thomas] - [5]

### ISSUE THREAD

**Issue by QuentinGollier** [code4policy/Team-A4#6]
**As** professionally pressed-for-time individuals

**We want** a pre-defined narrative we can easily follow

**So that** we don't have to make sense of it ourselves

------------------------------
**INVEST**
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

-------
**Definition of done:**
- [x] Their is a clear link from one section to the other, with a paragraph that links sections logically
- [x] Each section has a set of issues that are clearly labelled in the beginning, that insist on why this section is crucial to understanding the industry
- [x] Each section has a short conclusion that recaps the stakes and offers a quick look-back at its key insights

------
**Tasks:**

- [x] Write copy for the linking paragraphs
- [x] Write copy for the key issues of each section and insert
- [x] Block text for the issues, the concluding paragraph
- [x] Potentially support takeaways visually (e.g. highlighted box)
- [x] Insert code into the website's main branch
